eCommerce/Admins/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField,SubmitField, FloatField, IntegerField
from wtforms.validators import DataRequired, Length, ValidationError, InputRequired
from eCommerce.models import Product

def validate_unique_detail(form, detail_typed_into_form): # always give form, pore use hobe
   product_with_this_detail = Product.query\
                                    .filter_by(detail=detail_typed_into_form.data)\
                                    .first()
   if product_with_this_detail:
      raise ValidationError("That product is already there.")

  
class AddProductForm(FlaskForm):  
   name = StringField("Product Name", validators=[DataRequired()
                                                ,Length(max=20)])
   detail = StringField("Product Detail", validators=[DataRequired()
                                                ,Length(max=40), validate_unique_detail])
   price = FloatField("Product Price",  validators=[ InputRequired()])

   stock = IntegerField("Quantity",  validators=[ InputRequired()])
   picture = FileField("Insert Image", validators=[FileAllowed( ['jpg', 'png', 'jpeg'] )])
   submit = SubmitField("Submit")
   
   def validate_stock(self, stock):
      if stock.data < 0 :
         raise ValidationError('Quantity must be a positive integer')
      
   def validate_price(self, price):
      if price.data <= 0 :
         raise ValidationError('Quantity must be a positive integer')

   

class UpdateProductForm(FlaskForm):

   def __init__(self, product_detail, *args, **kwargs):
      self.product_detail = product_detail
      super().__init__( *args, **kwargs)

   name = StringField("Product Name", validators=[DataRequired()
                                                ,Length(max=20)])
   detail = StringField("Product Detail", validators=[DataRequired()
                                                ,Length(max=40)])
   price = FloatField("Product Price", validators=[ InputRequired()])

   stock = IntegerField("Quantity", validators=[InputRequired()])
   picture = FileField("Insert Image", validators=[FileAllowed( ['jpg', 'png', 'jpeg'] )])
   submit = SubmitField("Update")


   def validate_detail(self, detail):

      if detail.data != self.product_detail:
         detail = Product.query.filter_by(detail=detail.data).first()
         if detail:
               raise ValidationError('That detail is already there')
         
   def validate_stock(self, stock):
      if stock.data < 0 :
         raise ValidationError('Quantity must be a positive integer')
      
   def validate_price(self, price):
      if price.data <= 0 :
         raise ValidationError('Check price again')

eCommerce/Admins/routes.py
from eCommerce import db, app
from flask import Blueprint,render_template, redirect, request, url_for, flash
from eCommerce.models import Product, Admin
from eCommerce.Admins.forms import AddProductForm, UpdateProductForm
from eCommerce.common_froms import SearchForm
from eCommerce.Admins.utils import renameAndSave
import os

admins = Blueprint('admins', __name__, template_folder='templates')


search_term_before_edit=''
page_before_edit=0


@admins.route("/admin/search/<string:search_term>")
def adminSearch(search_term):
    
    page = request.args.get('page',1,type=int)
    paginated_searched_items = Product.query.filter( Product.name.contains(search_term) ).order_by(Product.id.desc()).paginate(page=page, per_page=10)

    global page_before_edit
    global search_term_before_edit
    page_before_edit = page
    search_term_before_edit = search_term

    return render_template('admin_searched_items.html', title='Searched Items', paginated_searched_items=paginated_searched_items, search_term=search_term)


@admins.route("/admin", methods=['GET', 'POST'])
def home():

    admin = Admin.query.first() # Demo current_admin
    
    form = SearchForm()
    if form.validate_on_submit():
        
        return redirect(url_for('admins.adminSearch', search_term=form.search_term.data))


    return render_template('admin_home.html', admin=admin, form=form)



@admins.route("/admin/add", methods=['GET', 'POST'])
def addProduct():

    form = AddProductForm()

    if form.validate_on_submit():
        
        new_product = Product(name = form.name.data
                            , detail = form.detail.data
                            , price = form.price.data
                            , stock = form.stock.data
                            )
        if form.picture.data:
            new_product.picture = renameAndSave(form.picture.data)

        db.session.add(new_product)
        db.session.commit()

        flash("The product has been added", 'success')

        form = AddProductForm(formdata=None)
        
    return render_template('add_product.html', title='Add Product', form=form)


@admins.route("/admin/product/<int:id>", methods=['GET', 'POST'])
def updateProduct(id):

    product = Product.query.get(id)

    form = UpdateProductForm(product.detail)

    if form.validate_on_submit():

        
        product.name = form.name.data
        product.detail = form.detail.data
        product.price = form.price.data
        product.stock = form.stock.data

        if form.picture.data:

            # Deleting old picture
            picture_name = product.picture

            if picture_name != 'default.jpg':
                os.remove(os.path.join(app.root_path, 'static','images' , picture_name ))

            # Deleted old picture

            product.picture = renameAndSave(form.picture.data)


        db.session.commit()

        flash(f"The product with ID {product.id} has been Updated", 'success')

        return redirect(url_for('admins.home')+f'/search/{search_term_before_edit}?page={page_before_edit}')

    elif request.method == 'GET':

        form.name.data = product.name
        form.detail.data = product.detail
        form.price.data = product.price
        form.stock.data = product.stock
    
    return render_template('update_product.html', title='Update Product', product=product, form=form)



@admins.route("/admin/product/<int:id>/delete", methods=['POST'])
def deleteProduct(id):

    product = Product.query.get_or_404(id)

    # Deleting image
    picture_name = product.picture

    if picture_name != 'default.jpg':
        os.remove(os.path.join(app.root_path, 'static','images' , picture_name )) 

    db.session.delete(product)
    db.session.commit()

    flash(f'Product with ID {id} has been deleted successfully', 'success')

    return redirect(url_for('admins.home')+f'/search/{search_term_before_edit}?page={page_before_edit}')

eCommerce/Admins/templates/add_product.html
{% extends 'admin_layout.html' %}

{% block content %}

<div class="container">
    <div class="content-section mt-5">
        <form action="" method="post" enctype="multipart/form-data"> <!--  THIS IS VERY VERY IMPORTAN "enctype" --> 
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"><h1>Add New Product</h1></legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
    
                    {% if form.name.errors %}
    
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.detail.label(class="form-control-label") }}
    
                    {% if form.detail.errors %}
    
                        {{ form.detail(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.detail.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.detail(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.price.label(class="form-control-label") }}
    
                    {% if form.price.errors %}
    
                        {{ form.price(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.price.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.price(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.stock.label(class="form-control-label") }}
    
                    {% if form.stock.errors %}
    
                        {{ form.stock(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.stock.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.stock(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label(class="form-control-label") }}
    
                    {% if form.picture.errors %}
    
                        {{ form.picture(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.picture.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.picture(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
    
            <div class=" form-group mt-3">{{ form.submit(class='btn btn-primary') }}</div>
        </form>
    </div>

</div>

{% endblock %}

eCommerce/Admins/templates/admin_home.html
{% extends 'admin_layout.html' %}

{% block content %}


<div class="container">
    <div class="content-section mt-5 bg-light p-5 row">

        <div class="col-lg-8 row">
            <b class="col-2">ID   </b>    <b class="col-1"> :</b>    <p class="col-9">{{ admin.id }}</p>
            <b class="col-2">Name </b>    <b class="col-1"> :</b>    <p class="col-9">{{ admin.name }}</p>
            <b class="col-2">Email</b>    <b class="col-1"> :</b>    <p class="col-9">{{ admin.email }}</p>
        </div>

        <div class="col-lg-4">
            <form action="" method="post" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                  {{ form.search_term.label(class="form-label") }}
                  {{ form.search_term(class="form-control" ) }}
                </div>

                {{ form.submit(class="btn btn-primary") }}
              </form>
        </div>
    </div>
</div>

{% endblock %}

eCommerce/Admins/templates/admin_layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        {% if title %}
            <title>Admin {{ title }}</title>
        {% else %}
            <title>Admin Home</title>
        {% endif %}

        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <script>
            function clearFlash(className){
                const flashed_messages = document.getElementsByClassName(className)
                const myTimeout = setTimeout(myGreeting, 3000);
                
                function myGreeting() {
                    $("."+className).fadeOut(1000);
                }
            }
        </script>

        
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href=" {{ url_for('static', filename='styles.css') }} " rel="stylesheet" />
    </head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <span class="navbar-brand me-4 text-primary">Admin's Panel</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ url_for('admins.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('admins.addProduct') }}">Add</a>
              </div>
            </div>
        </div>
    </nav>
    
    <main role="main" class="container">
        <div class="row">

            <div class="col-md-2"></div>

            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} flash_message_js">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <script>
                            clearFlash('flash_message_js')
                        </script>
                    {% endif %}
                {% endwith %}

                {% block content %} {% endblock %}
            </div>

            <div class="col-md-2"></div>

        </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</body>
</html>

eCommerce/Admins/templates/admin_searched_items.html
{% extends 'admin_layout.html' %}

{% block content %}


{% if paginated_searched_items.items%}

  <h1 class="my-4">Results for "{{ search_term }}"</h1>

  <table class="table table-striped table-dark mt-4">

    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Detail</th>
            <th scope="col">Stock</th>
            <th scope="col">Price</th>
            <th scope="col"></th>
        </tr>
    </thead>

    <tbody>
        {% for item in paginated_searched_items.items %}
            <tr id="divLink">
                <td scope="row">{{ item.id }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.detail }}</td>
                <td>{{ item.stock }}</td>
                <td>{{ item.price }}</td>
                <td><a class="btn btn-outline-primary" href="{{url_for('admins.updateProduct', id=item.id)}}">Edit</a></td>
            </tr>
        {% endfor %}

    </tbody>

  </table>
    {% for page in paginated_searched_items.iter_pages(left_edge=1, left_current=1, right_edge=1, right_current=1) %}
        {% if page %}
            {% if paginated_searched_items.page == page %}
                <a href="{{ url_for('admins.adminSearch', search_term=search_term, page=page) }}" class="btn btn-dark">{{ page }}</a>
            {% else %}
                <a href="{{ url_for('admins.adminSearch', search_term=search_term, page=page) }}" class="btn btn-outline-dark">{{ page }}</a>
            {% endif %}
        {% else %}
            <span class="text-dark">...</span>
        {% endif %}
    {% endfor %}

{% else %}
    <h1 class="my-4">No item for "{{ search_term }}"</h1>
{% endif %}

{% endblock %}

eCommerce/Admins/templates/update_product.html
{% extends 'admin_layout.html' %}

{% block content %}

<form id="deleteForm" action="{{url_for('admins.deleteProduct', id=product.id)}}" method="post" class="bg-danger">
</form>

<div class="container">
    <div class="content-section mt-5 bg-light p-5 row">

        <h1>Product with ID {{product.id}} Update Here</h1>
        <div class="row my-2">
            <div class="col-lg-5">
                <img class="img-fluid" src="{{ url_for('static', filename = 'images/' + product.picture) }}" alt="">
            </div>
            <div class="col-lg-7">
                <form action="" method="post" enctype="multipart/form-data"> <!--  THIS IS VERY VERY IMPORTAN "enctype" --> 
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <div class="form-group">
                        {{ form.name.label(class="form-control-label") }}
        
                        {% if form.name.errors %}
        
                            {{ form.name(class="form-control form-control-sm is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.name.errors %}
                                    <span> {{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                                {{ form.name(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.detail.label(class="form-control-label") }}
            
                            {% if form.detail.errors %}
            
                                {{ form.detail(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.detail.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.detail(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.price.label(class="form-control-label") }}
            
                            {% if form.price.errors %}
            
                                {{ form.price(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.price.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.price(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.stock.label(class="form-control-label") }}
            
                            {% if form.stock.errors %}
            
                                {{ form.stock(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.stock.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.stock(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.picture.label(class="form-control-label") }}
            
                            {% if form.picture.errors %}
            
                                {{ form.picture(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.picture.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.picture(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    
                    <div class="container form-group my-3">

                        {{ form.submit(class='btn btn-outline-primary me-2') }}
                        
                        <input form="deleteForm" type="submit" value="Delete" class="btn btn-outline-danger" >
                    </div>

                </form>

            </div>

        </div>
    </div>
</div>

{% endblock %}