eCommerce/Admins/routes.py
from eCommerce import db, app
from flask import Blueprint,render_template, redirect, request, url_for, flash
from eCommerce.models import Product, Admin
from eCommerce.Admins.forms import AddProductForm, UpdateProductForm
from eCommerce.common_froms import SearchForm
from eCommerce.Admins.utils import renameAndSave
import os

admins = Blueprint('admins', __name__, template_folder='templates')


search_term_before_edit=''
page_before_edit=0


@admins.route("/admin/search/<string:search_term>")
def adminSearch(search_term):
    
    page = request.args.get('page',1,type=int)
    paginated_searched_items = Product.query.filter( Product.name.contains(search_term) ).order_by(Product.id.desc()).paginate(page=page, per_page=10)

    global page_before_edit
    global search_term_before_edit
    page_before_edit = page
    search_term_before_edit = search_term

    return render_template('admin_searched_items.html', title='Searched Items', paginated_searched_items=paginated_searched_items, search_term=search_term)


@admins.route("/admin", methods=['GET', 'POST'])
def home():

    admin = Admin.query.first() # Demo current_admin
    
    form = SearchForm()
    if form.validate_on_submit():
        
        return redirect(url_for('admins.adminSearch', search_term=form.search_term.data))


    return render_template('admin_home.html', admin=admin, form=form)



@admins.route("/admin/add", methods=['GET', 'POST'])
def addProduct():

    form = AddProductForm()

    if form.validate_on_submit():
        
        new_product = Product(name = form.name.data
                            , detail = form.detail.data
                            , price = form.price.data
                            , stock = form.stock.data
                            )
        if form.picture.data:
            new_product.picture = renameAndSave(form.picture.data)

        db.session.add(new_product)
        db.session.commit()

        flash("The product has been added", 'success')

        form = AddProductForm(formdata=None)
        
    return render_template('add_product.html', title='Add Product', form=form)


@admins.route("/admin/product/<int:id>", methods=['GET', 'POST'])
def updateProduct(id):

    product = Product.query.get(id)

    form = UpdateProductForm(product.detail)

    if form.validate_on_submit():

        
        product.name = form.name.data
        product.detail = form.detail.data
        product.price = form.price.data
        product.stock = form.stock.data

        if form.picture.data:

            # Deleting old picture
            picture_name = product.picture

            if picture_name != 'default.jpg':
                os.remove(os.path.join(app.root_path, 'static','images' , picture_name ))

            # Deleted old picture

            product.picture = renameAndSave(form.picture.data)


        db.session.commit()

        flash(f"The product with ID {product.id} has been Updated", 'success')

        return redirect(url_for('admins.home')+f'/search/{search_term_before_edit}?page={page_before_edit}')

    elif request.method == 'GET':

        form.name.data = product.name
        form.detail.data = product.detail
        form.price.data = product.price
        form.stock.data = product.stock
    
    return render_template('update_product.html', title='Update Product', product=product, form=form)



@admins.route("/admin/product/<int:id>/delete", methods=['POST'])
def deleteProduct(id):

    product = Product.query.get_or_404(id)

    # Deleting image
    picture_name = product.picture

    if picture_name != 'default.jpg':
        os.remove(os.path.join(app.root_path, 'static','images' , picture_name )) 

    db.session.delete(product)
    db.session.commit()

    flash(f'Product with ID {id} has been deleted successfully', 'success')

    return redirect(url_for('admins.home')+f'/search/{search_term_before_edit}?page={page_before_edit}')

eCommerce/Carts/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from eCommerce.common_froms import SearchForm
from eCommerce.models import Product


carts = Blueprint('carts', __name__, template_folder='templates')



@carts.route("/cart", methods=['Get', 'POST'])
def cart():

    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('users.userSearch', search_term=form.search_term.data,  numberOfItems=test_user.numberOfItems))

    products = []
    total = 0

    for i in range( len(test_user.cart) ):

        product = Product.query.get(test_user.cart[i])
        products.append(product)

        total += product.price * test_user.quantity_list[i]

    return render_template('user_cart.html',  form=form,   numberOfItems=test_user.numberOfItems,
                            products=products, quantity_list=test_user.quantity_list, total=total)


@carts.route("/actionInCart/<int:index>/<string:sign>", methods=['POST'])
def actionInCart(index, sign):
    global test_user


    index = index-1


    test_user.updateCart(index=index, sign=sign)


    return redirect(url_for('users.cart'))


@carts.route("/deleteInCart", methods=['POST'])
def deleteInCart():
    
    index= request.args.get('index',0, type=int )-1

    global test_user


    test_user.deleteFromCart(index=index)

    return redirect(url_for('users.cart'))



@carts.route("/pay", methods=['GET'])
def pay():
    return render_template('pay.html')

eCommerce/Users/routes.py
from flask import Blueprint,render_template, redirect, request, url_for, flash
from eCommerce.models import Product
from eCommerce.common_froms import SearchForm
import json


users = Blueprint('users', __name__,
                  template_folder='templates')


class UserClass:

    default_quantity = 1

    def __init__(self):
        self.cart=[]
        self.quantity_list = []
        self.numberOfItems = 0

    def addItemToCart(self, product_id):

        if product_id not in self.cart:

            self.cart.append(product_id)
            self.quantity_list.append(UserClass.default_quantity)
            self.numberOfItems += 1 #one product was added

    def updateCart(self, index, sign):


        if sign == "+":
            self.quantity_list[index] += 1
            self.numberOfItems += 1 #one product was added

        if sign == "-":

            if self.quantity_list[index] > 0:
                self.quantity_list[index] -=1

                self.numberOfItems -= 1 #one product was removed
        for index,product in enumerate(self.cart):
            print(str(product)+'\t'+str(self.quantity_list[index])+'\n')


    def deleteFromCart(self, index):
            
        self.cart.pop(index)
        self.numberOfItems -= self.quantity_list[index]
        self.quantity_list.pop(index)


test_user = UserClass()


@users.route("/search/<string:search_term>", methods=['GET', 'POST'])
def userSearch(search_term):
    
    page = request.args.get('page',1,type=int)
    paginated_products = Product.query.filter(Product.name.contains(search_term)).filter(Product.stock>0).order_by(Product.id.desc()).paginate(page=page, per_page=20)

    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('users.userSearch', search_term=form.search_term.data,  numberOfItems=test_user.numberOfItems))
    
    items_in_cart = test_user.cart

    return render_template('user_searched_items.html', title='Searched Items', form=form,
                            paginated_products=paginated_products, search_term=search_term, numberOfItems=test_user.numberOfItems, items_in_cart=items_in_cart)




@users.route("/", methods=['GET', 'POST'])
def home():
    # Search bar
    page = request.args.get('page', 1, type=int)
    paginated_products = Product.query.filter(Product.stock>0).order_by(Product.id.desc()).paginate(page=page, per_page=20)

    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('users.userSearch', search_term=form.search_term.data,  numberOfItems=test_user.numberOfItems))
    

    items_in_cart = test_user.cart
    
    return render_template('home.html', paginated_products=paginated_products, form=form,   numberOfItems=test_user.numberOfItems, items_in_cart=items_in_cart)

@users.route("/about")
def about():
    return render_template('about.html', title='About')

@users.route("/addToCart", methods=['POST'])
def addToCart():
    global test_user

    product_id = request.form['product_id'] # 'product_id' corresponds to the name inside <input name='product_id'  ......>

    test_user.addItemToCart(product_id=product_id)

    return "Added to cart successfully"


@users.route("/cart", methods=['Get', 'POST'])
def cart():

    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('users.userSearch', search_term=form.search_term.data,  numberOfItems=test_user.numberOfItems))

    products = []
    total = 0

    for i in range( len(test_user.cart) ):

        product = Product.query.get(test_user.cart[i])
        products.append(product)

        total += product.price * test_user.quantity_list[i]

    return render_template('user_cart.html',  form=form,   numberOfItems=test_user.numberOfItems,
                            products=products, quantity_list=test_user.quantity_list, total=total)


@users.route("/actionInCart/<int:index>/<string:sign>", methods=['POST'])
def actionInCart(index, sign):
    global test_user


    index = index-1


    test_user.updateCart(index=index, sign=sign)


    return redirect(url_for('users.cart'))


@users.route("/deleteInCart", methods=['POST'])
def deleteInCart():
    
    index= request.args.get('index',0, type=int )-1

    global test_user


    test_user.deleteFromCart(index=index)

    return redirect(url_for('users.cart'))



@users.route("/pay", methods=['GET'])
def pay():
    return render_template('pay.html')
    

eCommerce/templates/admin_layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        {% if title %}
            <title>Admin {{ title }}</title>
        {% else %}
            <title>Admin Home</title>
        {% endif %}

        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <script>
            function clearFlash(className){
                const flashed_messages = document.getElementsByClassName(className)
                const myTimeout = setTimeout(myGreeting, 3000);
                
                function myGreeting() {
                    $("."+className).fadeOut(1000);
                }
            }
        </script>

        
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href=" {{ url_for('static', filename='styles.css') }} " rel="stylesheet" />
    </head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand me-4" href="#">Admin's Panel</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ url_for('admins.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('admins.addProduct') }}">Add</a>
              </div>
            </div>
        </div>
    </nav>
    
    <main role="main" class="container">
        <div class="row">

            <div class="col-md-2"></div>

            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} flash_message_js">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <script>
                            clearFlash('flash_message_js')
                        </script>
                    {% endif %}
                {% endwith %}

                {% block content %} {% endblock %}
            </div>

            <div class="col-md-2"></div>

        </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>


</body>
</html>

eCommerce/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        {% if title %}
            <title>E-commerce {{ title }}</title>
        {% else %}
            <title>E-commerce Home</title>
        {% endif %}
        
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href=" {{ url_for('static', filename='styles.css') }} " rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-success bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">E-commerce Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link" aria-current="page" href=" {{ url_for('home') }} ">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href=" {{ url_for('about') }} ">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-success" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-success text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="#">login</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Register</a></li>
                 
                    </ul>
                </div>
            </div>
        </nav>


        {% block content %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>


        <!-- Footer-->
        <footer class="py-3 bg-success fixed-bottom">
            <div class="container-sm"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <!-- Core theme JS-->
        <script></script>
    </body>
</html>

eCommerce/templates/search_bar.html
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="d-flex me-3 my-1">
    {{ form.search_term(class="form-control me-2" ) }}
    {% if 'admins' in request.endpoint %}
        {{ form.submit(class="btn btn-primary") }}
    {% elif 'users' in request.endpoint %}
        {{ form.submit(class="btn btn-success") }}
    {% endif %}
    </div>
</form>

eCommerce/templates/searched_items.html
{% extends 'admin_layout.html' %}

{% block content %}


{% if items%}

  <h1 class="my-4">Results for "{{ search_term }}"</h1>

  <table class="table table-striped table-dark mt-4">

    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Stock</th>
            <th scope="col">Price</th>
            <th scope="col"></th>
        </tr>
    </thead>

    <tbody>
        {% for item in items %}
            <tr id="divLink">
                <th scope="row">{{ item.id }}</th>
                <td>{{ item.name }}</td>
                <td>{{ item.stock }}</td>
                <td>{{ item.price }}</td>
                <td><a class="btn btn-outline-primary" href="{{url_for('updateProduct', id=item.id)}}">Edit</a></td>
            </tr>
        {% endfor %}

    </tbody>

  </table>

{% else %}
    <h1 class="my-4">No item for "{{ search_term }}"</h1>
{% endif %}

{% endblock %}

eCommerce/templates/user_layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        {% if title %}
            <title>E-commerce {{ title }}</title>
        {% else %}
            <title>E-commerce Home</title>
        {% endif %}
        
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href=" {{ url_for('static', filename='styles.css') }} " rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    </head>
    <body class=" bg-light">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-success bg-light fixed-top">
            <div class="container px-4 px-lg-5">
                <b class="navbar-brand text-success">E-commerce Shop</b>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto my-1 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link" aria-current="page" href=" {{ url_for('users.home') }} ">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href=" {{ url_for('users.about') }} ">About</a></li>
                        
                    </ul>
                     <!-- Search Bar -->

                    {% if  request.endpoint != 'users.about' and request.endpoint != 'users.pay' %}
                        {% include 'search_bar.html' %}

                    <a class="btn btn-outline-success my-1 d-flex"  href="{{ url_for('carts.cart') }}">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-success text-white ms-1 rounded-pill my-auto" id="numberOfItems">{{ numberOfItems }}</span>
                    </a>

                    {% endif %}

                    <ul class="navbar-nav mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="#">login</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Register</a></li>
                 
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid my-5">
            {% block content %}{% endblock %}
        </div>



        <!-- Footer-->
        <footer class="py-2 bg-success fixed-bottom">
            <div class="container-sm"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script></script>
    </body>
</html>